#!/bin/sh
#
# Load modules from /etc/modules

load_modules()
{
        filename="/etc/modules"

        while read -r line
        do
                module="$line"
                modprobe $module
        done < "$filename"
}


case "$1" in
        start)
                load_modules
                ;;
        stop)
                ;;
        restart|reload)
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

