#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
  # Be sure we have all the keys generated
  if [ -f /etc/ssh/ssh_host_dsa_key -a -f /etc/ssh/ssh_host_dsa_key.pub -a -f /etc/ssh/ssh_host_rsa_key -a -f /etc/ssh/ssh_host_rsa_key.pub -a -f /etc/ssh/ssh_host_ecdsa_key -a -f /etc/ssh/ssh_host_ecdsa_key.pub -a -f /etc/ssh/ssh_host_ed25519_key -a -f /etc/ssh/ssh_host_ed25519_key.pub -a -f /etc/ssh/ssh_keys_done ]; then
    echo "SSH keys already generated"
  else
    echo "Generate SSH keys"

    # Remount partition in read-write
    /usr/local/bin/rw.sh

	  # Create any missing keys
	  /usr/bin/ssh-keygen -A

    # Make sure keys are written to disk 
    sync;
    touch /etc/ssh/ssh_keys_done
    sync;

    # Remount partition in read-only
    /usr/local/bin/ro.sh
  fi

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

