HELLO_AUTOTOOLS_SOURCE = hello-autotools.tar.bz2
HELLO_AUTOTOOLS_SITE = file://$(BR2_EXTERNAL_SV_CUSTOM_PATH)/sources
HELLO_AUTOTOOLS_LICENSE = GPL-3.0+
HELLO_AUTOTOOLS_LICENSE_FILES = COPYING
HELLO_AUTOTOOLS_AUTORECONF = YES

$(eval $(autotools-package))
