HELLO_MODULE_SOURCE = hello-module.tar.bz2 
HELLO_MODULE_SITE = file://$(BR2_EXTERNAL_SV_CUSTOM_PATH)/sources
HELLO_MODULE_LICENSE = BSD-3-Clause
HELLO_MODULE_LICENSE_FILES = LICENSE
HELLO_MODULE_DEPENDENCIES = linux

define HELLO_MODULE_BUILD_CMDS
	$(MAKE) -C $(@D) $(LINUX_MAKE_FLAGS) KERNELDIR=$(LINUX_DIR)
endef

define HELLO_MODULE_INSTALL_TARGET_CMDS
	$(MAKE) -C $(@D) $(LINUX_MAKE_FLAGS) KERNELDIR=$(LINUX_DIR) modules_install
endef

$(eval $(generic-package))
